### ISSUE TITLE
에코 서버 만들기

### ISSUE THREAD

**Issue by jimin52** [JaeHwan-s-WebServeClass/webserver-nginx#1]
### Todo
- [x] echo server 레퍼런스 공부하기 (코드 분석 및 주석 달기)
- [x] echo server 만들어서 작동시켜보기
- [x] 어떤 식으로 객체를 구성할지 설계해보기
- [x] 어떤 식으로 객체간에 메시지를 주고받을지 pseudo code 만들어보기
